# SAM template for CodeBuild
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for inserting thread records within a DynamoDB table.
Resources:
  PostThreadsFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/post-threads-fx-1.0-SNAPSHOT.jar
      Handler: com.revature.postThread.PostThreadsHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - arn:aws:lambda:us-east-1:857547178254:function:post-threads-fx